// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbErLVez6B0-pBRevkxPqKdHAiGh0Lz40',
    appId: '1:913872346580:web:21f8d2abcc463107058a41',
    messagingSenderId: '913872346580',
    projectId: 'instagram-clone-eab3d',
    authDomain: 'instagram-clone-eab3d.firebaseapp.com',
    storageBucket: 'instagram-clone-eab3d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZMETOKbBHEEj1ABoFhvIALtvdRyf9ftc',
    appId: '1:913872346580:android:7bcfc9b1e6ad9ece058a41',
    messagingSenderId: '913872346580',
    projectId: 'instagram-clone-eab3d',
    storageBucket: 'instagram-clone-eab3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK3HpKPhnhRIdZkzNLaQoJks2wSJ77Sog',
    appId: '1:913872346580:ios:a2ea3bec121e58a3058a41',
    messagingSenderId: '913872346580',
    projectId: 'instagram-clone-eab3d',
    storageBucket: 'instagram-clone-eab3d.appspot.com',
    iosClientId: '913872346580-0016rr62047v6bnvri8kt56972e6kd83.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK3HpKPhnhRIdZkzNLaQoJks2wSJ77Sog',
    appId: '1:913872346580:ios:a2ea3bec121e58a3058a41',
    messagingSenderId: '913872346580',
    projectId: 'instagram-clone-eab3d',
    storageBucket: 'instagram-clone-eab3d.appspot.com',
    iosClientId: '913872346580-0016rr62047v6bnvri8kt56972e6kd83.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
